### ISSUE TITLE
Plugging a GUI?

### ISSUE THREAD

**Issue by ptkovsky** [jo-sm/twitch#2]
Hello again.

So, sometimes I'm getting tired of using any of the terminal emulators and just want to fuck around clicking on different streams. I can even use Safari for the actual Twitch page, I also have Streamlink Twitch GUI installed, where you can browse stuff with a little less impact on system resource usage and start a stream playback using a variety of players of your choice.

As and example mechanic, IINA has a functionality of a simple browser plugin where you can just install it and click on the stream in the browser for the playback start. It's not exactly convenient, but it's doing something, nevertheless.

Anyway, is there an actual theoretical possibility of sort-of-fast plugging this little gem into a GUI? Like, maybe writing a quick script or so will do the job just fine? Should I even consider writing a feature request here https://github.com/streamlink/streamlink-twitch-gui/issues/new? Obviously it's only meant for Streamlink, but whatever happens?

**Comment by jo-sm** [comment]
Hey @ptkovsky, I've thought about this in the past, primarily plugging this functionality into a web app I made before to search for vods as the cross-domain functionality this uses wouldn't work in a browser and would require some intermediary, since Twitch doesn't allow you to access the APIs through normal means. 

As for a dedicated desktop GUI, I hadn't given it much thought, but it might be nifty, especially if it included the Twitch chat on the side. I also have been interested in making a QT application for something else, so I might investigate some Ruby QT works and see where it goes.

However, making a GUI would be a long (or very long) way off, and I'd rather get a more powerful terminal based version of this first (that might integrate Twitch chat, fast forward, restricted videos, etc.) that utilizes the functionality in this gem. I'll keep this issue open in the mean time. As far as creating an issue for Streamlink Twitch GUI, since it uses JS this codebase isn't compatible unfortunately. I'd say if you have another method for just browsing streams, I'd use that, since a GUI implementation would be a while away (have to learn QT first!).

**Comment by ptkovsky** [comment]
Cool! Thanks for your detailed explanations of the thought process, loving it. Wish there would be more critically thinking people around watching twitch on their Macs caring about power consumption and noise figures. Yeah, I do realize that this can be a really complicated task, especially if you’re willing to implement it properly. Guess we'd have to wait and see how it goes...

**Comment by jo-sm** [comment]
I have some plans to make the terminal version more robust, for example adding in chat for both vods and live streams, subscriber only videos, and attempting to fix some issues with Quicktime not properly handling poor internet connections, so be on the look out for it!

**Comment by jo-sm** [comment]
Unfortunately, as shown by this issue being over 2.5 years old with no relevant updates, it's unlikely I'll get to implementing a GUI, or even some of the other ideas I have such as integrating chat replays or subscriber only videos. The main limiting factor is the API around QuickTime (QT); the last time I looked up about QuickTime's APIs it seemed it would be challenging to integrate between QT and my Ruby script and I don't think I'll have the time to devote to finding a novel solution to the issues I found before. This limits integrating things like poor connection handling and chat replays. 

That said, I do think this program is valuable - I use it often because even on a newer MacBook on Safari, Twitch eats CPU and thus eats battery with their browser player, which is unacceptable to me. I do keep this utility updated (two commits/releases this week), and so if a request for some of the features I mentioned above come up, I'll look a bit more. Until then, I'll close this issue.
